arm: ioremap: Fix pci_remap_iospace() when CONFIG_MMU unset
The custom ARM version of pci_remap_iospace() is defined in
arch/arm/mm/ioremap.c, which is only built when CONFIG_MMU=y.

When CONFIG_MMU is unset there's no implementation, which causes errors:

  arm-linux-gnueabi-ld: arch/arm/mach-dove/pcie.o: in function `dove_pcie_setup':
  >> pcie.c:(.init.text+0x170): undefined reference to `pci_remap_iospace'
  arm-linux-gnueabi-ld: drivers/pci/pci.o: in function `devm_pci_remap_iospace':
  (.text+0x1a84): undefined reference to `pci_remap_iospace'

When CONFIG_MMU is unset, leave the pci_remap_iospace macro undefined so we
use the default pci_remap_iospace() implementation from drivers/pci/pci.c,
which just returns failure.

[bhelgaas: commit log]
Fixes: bc02973a06a6 ("arm: ioremap: Implement standard PCI function pci_remap_iospace()")
Link: https://lore.kernel.org/r/20220714185700.6137-1-pali@kernel.org
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Pali Rohár <pali@kernel.org>
Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>