Fixup: BACKPORT: ipts: Cleanup ipts-i915 to pass checkpatch
When cherry-picking the commit b7c60a63bd916ab6c0e779d9b7a8d10b4f98a9e0
(ipts: Cleanup ipts-i915 to pass checkpatch), the following line added
accidentally.

        drivers/gpu/drm/i915/i915_irq.c:40:10: fatal error: intel_psr.h: No such file or directory
           40 | #include "intel_psr.h"
              |          ^~~~~~~~~~~~~

This commit fixes up the accidentally added line by removing it.