ntfs-fix-use-after-free-in-ntfs_ucsncmp-v3-checkpatch-fixes
ERROR: code indent should use tabs where possible
#27: FILE: fs/ntfs/attrib.c:598:
+^I^I               a->name_length * sizeof(ntfschar);$

total: 1 errors, 0 warnings, 8 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/ntfs-fix-use-after-free-in-ntfs_ucsncmp-v3.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: ChenXiaoSong <chenxiaosong2@huawei.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>